### ISSUE TITLE
Which version of visual studio is used to build this project ?

### ISSUE THREAD

**Issue by zbhuang** [JoeyEremondi/treewidth-memoization#1]
Good to see this project, and I am interested to see how it works.
I wonder - which version of visual studio you are using to build this project ?
I try to use visual studio 2010 and it failed.

Thanks.

**Comment by JoeyEremondi** [comment]
I'm currently on VS2015, though it will also build with Clang. Make sure to have C++11 enabled, I use auto and other modern features quite a bit. Please note that this is a work in progress, I'm working on it right now! Hopefully there will be something more coherent in a couple of months. The only one that gets decent performance right now is BottomUpTW, but I'm working on the others.

**Comment by zbhuang** [comment]
Thanks for the update, I will check.
